[project]
name = "mimic3-db-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "peft>=0.20.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "torch>=2.13.0",
    "transformers>=5.16.1",
    "xgboost>=3.4.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
